name: Minh Ly
description: Blogging about anything of programing
meta_description: "Blogging about javascript, front-end, everythings about javascript"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: 'http://lytm.github.com/'
google_analytics: 'UA-76600560-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'lytm.github.com'
author:         'LyTm'